import {
  Plane,
  Martini,
  Umbrella,
  UserRound,
  Users,
  Droplets,
  Flower2,
  Sailboat,
  Waves,
  Mountain,
  MountainSnow,
  ThumbsUp,
  CalendarClock,
  Timer,
  MapPin,
  Euro,
  Star,
  Briefcase,
  type LucideIcon,
} from "lucide-react";
import type { FilterIconName } from "@/data/filters";

export const filterIconMap: Record<FilterIconName, LucideIcon> = {
  plane: Plane,
  martini: Martini,
  umbrella: Umbrella,
  "user-round": UserRound,
  users: Users,
  droplets: Droplets,
  flower: Flower2,
  sailboat: Sailboat,
  waves: Waves,
  mountain: Mountain,
  "mountain-snow": MountainSnow,
  "thumbs-up": ThumbsUp,
  "calendar-clock": CalendarClock,
  timer: Timer,
  "map-pin": MapPin,
  euro: Euro,
  star: Star,
  baggage: Briefcase,
};

/** Line-art accent colors matching the compact Reisearten reference cards. */
export const filterIconColor: Record<FilterIconName, string> = {
  plane: "text-[#3B82F6]",
  martini: "text-[#E39B1A]",
  umbrella: "text-[#12A89A]",
  "user-round": "text-[#6B7280]",
  users: "text-[#F97316]",
  droplets: "text-[#0EA5E9]",
  flower: "text-[#E94B8A]",
  sailboat: "text-[#2563EB]",
  waves: "text-[#0284C7]",
  mountain: "text-[#22A34A]",
  "mountain-snow": "text-[#6366F1]",
  "thumbs-up": "text-[#22C55E]",
  "calendar-clock": "text-[#E8A317]",
  timer: "text-[#EF4444]",
  "map-pin": "text-[#EF4444]",
  euro: "text-[#1B63EB]",
  star: "text-[#E8A317]",
  baggage: "text-[#3B82F6]",
};
